name: Upload Sample GeoJSON to S3

on:
  push:
    branches:
      - main
    paths:
      - 'assets/sample.geojson'

permissions:
  id-token: write
  contents: read

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: 'arn:aws:iam::132945991488:role/github-oidc-role'
          
      - name: Upload GeoJSON to S3
        run: |
          aws s3 cp assets/sample.geojson s3://sample-sample-sample-test/sample.geojson
