name: Upload GeoJSON to S3

on:
  push:
    branches:
      - main
    paths:
      - 'assets/sample.geojson'

permissions:
  contents: read

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload GeoJSON to S3
        run: |
          aws s3 cp assets/sample.geojson s3://riverdata-main-bucket2/river-data/sample.geojson
